### ISSUE TITLE
Default blue color in community files

### ISSUE THREAD

**Issue by DMW007** [DMW007/cnx-custom-theme#8]
### Communitys > Files 

The "Add" button has a blue border
```css
.lotusui30 .lotusColLeft .lotusGlobalActionBar .lotusBtn {
    background: #4178be;
        background-color: rgb(65, 120, 190);
    color: #FFF;
    border: 1px solid #3765a0;
    padding: 10px 0;
}
```

### Communitys > files > New file/folder dialog
The _abort_ button is blue

![grafik](https://user-images.githubusercontent.com/21245043/106734346-34223180-6613-11eb-85a4-1ba9eee307cf.png)

This is the case for all dialogs in the _add_ dropdown like adding folder/files, share with community.

--> We should keep this consistent, in personal files it's fixed with the secondary color (gray)
